controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

api_users_professions:
    path: /users/professions
    controller: App\Controller\UserController::getProfessions
    methods: [GET]